# **Importing Libraries**

In [33]:
import numpy as np
import pandas as pd
import ast

# **Loading Data**

In [34]:
jobs = pd.read_csv("/content/all_job_post.csv")
jobs

,job_id,category,job_title,job_description,job_skill_set
0,3902668440,HR,Sr Human Resource Generalist,SUMMARY\nTHE SR. HR GENERALIST PROVIDES HR EXP...,"['employee relations', 'talent acquisition', '..."
1,3905823748,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M..."
2,3905854799,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ..."
3,3905834061,HR,Chief Human Resources Officer,JOB TITLE: CHIEF HUMAN RESOURCES OFFICER (CHRO...,"['talent management', 'organizational developm..."
4,3906250451,HR,Human Resources Generalist (Hybrid Role),DESCRIPTION\n\n WHO WE ARE \n\nAVI-SPL IS A DI...,"['Microsoft Office', 'Data analysis', 'Employe..."
...,...,...,...,...,...
1162,3905299905,BUSINESS-DEVELOPMENT,Intern - Business Development,REQUIREMENTS\n\n DESCRIPTION & REQUIREMENTS \n...,"['MS Office Suite', 'PowerPoint', 'Excel', 're..."
1163,3885829894,BUSINESS-DEVELOPMENT,Business Development Representative,IT'S FUN TO WORK IN A COMPANY WHERE PEOPLE TRU...,"['Collaboration', 'Communication', 'Problem So..."
1164,3901649881,BUSINESS-DEVELOPMENT,Enterprise Business Development Representative...,JOIN OUR DYNAMIC AI TEAM AS AN ENTERPRISE BUSI...,"['Salesforce', 'data analysis', 'lead generati..."
1165,3904049863,BUSINESS-DEVELOPMENT,Senior Director Business Development,ROOM 8 GROUP IS THE WORLD’S FASTEST GROWING ST...,"['business development', 'sales', 'corporate s..."
1166,3904084138,BUSINESS-DEVELOPMENT,Global Business Development Partner - 100% Remote,EXCITING OPPORTUNITY: GLOBAL BUSINESS DEVELOPM...,"['strategic marketing', 'business development'..."

# **Data Exploration**

In [35]:
jobs.shape

(1167, 5)

In [36]:
jobs.head()

,job_id,category,job_title,job_description,job_skill_set
0,3902668440,HR,Sr Human Resource Generalist,SUMMARY\nTHE SR. HR GENERALIST PROVIDES HR EXP...,"['employee relations', 'talent acquisition', '..."
1,3905823748,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M..."
2,3905854799,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ..."
3,3905834061,HR,Chief Human Resources Officer,JOB TITLE: CHIEF HUMAN RESOURCES OFFICER (CHRO...,"['talent management', 'organizational developm..."
4,3906250451,HR,Human Resources Generalist (Hybrid Role),DESCRIPTION\n\n WHO WE ARE \n\nAVI-SPL IS A DI...,"['Microsoft Office', 'Data analysis', 'Employe..."

In [37]:
jobs.tail()

,job_id,category,job_title,job_description,job_skill_set
1162,3905299905,BUSINESS-DEVELOPMENT,Intern - Business Development,REQUIREMENTS\n\n DESCRIPTION & REQUIREMENTS \n...,"['MS Office Suite', 'PowerPoint', 'Excel', 're..."
1163,3885829894,BUSINESS-DEVELOPMENT,Business Development Representative,IT'S FUN TO WORK IN A COMPANY WHERE PEOPLE TRU...,"['Collaboration', 'Communication', 'Problem So..."
1164,3901649881,BUSINESS-DEVELOPMENT,Enterprise Business Development Representative...,JOIN OUR DYNAMIC AI TEAM AS AN ENTERPRISE BUSI...,"['Salesforce', 'data analysis', 'lead generati..."
1165,3904049863,BUSINESS-DEVELOPMENT,Senior Director Business Development,ROOM 8 GROUP IS THE WORLD’S FASTEST GROWING ST...,"['business development', 'sales', 'corporate s..."
1166,3904084138,BUSINESS-DEVELOPMENT,Global Business Development Partner - 100% Remote,EXCITING OPPORTUNITY: GLOBAL BUSINESS DEVELOPM...,"['strategic marketing', 'business development'..."

In [38]:
jobs.duplicated().sum()

np.int64(0)

In [39]:
jobs.T.duplicated().sum()

np.int64(0)

In [40]:
jobs.isnull().sum()

job_id             0
category           0
job_title          0
job_description    0
job_skill_set      0
dtype: int64

In [41]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           1167 non-null   int64
 1   category         1167 non-null   object
 2   job_title        1167 non-null   object
 3   job_description  1167 non-null   object
 4   job_skill_set    1167 non-null   object
dtypes: int64(1), object(4)
memory usage: 45.7+ KB

In [42]:
jobs['job_title'].value_counts().head(10)

job_title
Business Development Manager                 53
Human Resources Generalist                   34
Business Development Representative          33
Human Resources Manager                      28
Information Technology Support Specialist    16
Finance Manager                              15
Human Resources Business Partner             15
Director of Finance                          13
Human Resources Coordinator                  11
Information Technology Project Manager       11
Name: count, dtype: int64

In [43]:
jobs['category'].value_counts()

category
INFORMATION-TECHNOLOGY    240
BUSINESS-DEVELOPMENT      239
FINANCE                   236
SALES                     232
HR                        220
Name: count, dtype: int64

# **Preparing**

In [44]:
jobs.drop(columns=["job_id"], inplace=True)

In [45]:
jobs.columns

Index(['category', 'job_title', 'job_description', 'job_skill_set'], dtype='object')

In [46]:
tech_jobs = jobs[jobs["category"] == "INFORMATION-TECHNOLOGY"]

tech_jobs.shape

(240, 4)

In [47]:
tech_jobs["job_title"].value_counts().head(20)

job_title
Information Technology Support Specialist        16
Information Technology Project Manager           11
Director of Information Technology               10
Information Technology Manager                   10
Information Technology Project Coordinator       10
Information Technology Specialist                 7
Information Technology Technician                 6
Information Technology System Administrator       6
Information Technology Support Technician         5
Senior Information Technology Project Manager     5
Information Technology Help Desk                  5
Information Technology Security Analyst           3
Information Technology Sourcing Manager           3
Senior Information Technology Auditor             3
Information Technology Operations Manager         3
Entry-level Information Technology (IT) Role      3
Information Technology Asset Manager              3
Information Technology Administrator              3
Information Technology Business Analyst           3
Information Technology Business Consultant        3
Name: count, dtype: int64

In [48]:
tech_jobs.head()

,category,job_title,job_description,job_skill_set
220,INFORMATION-TECHNOLOGY,Information Technology Project Manager,JOB TITLE: PROJECT MANAGER LOCATION: TALLAHASS...,"['project management', 'application system dev..."
221,INFORMATION-TECHNOLOGY,Information Technology Security Analyst,FULL JOB DESCRIPTIONAS AN INFORMATION SECURITY...,"['Communication', 'Teamwork', 'Flexibility', '..."
222,INFORMATION-TECHNOLOGY,"Application Analyst I, Day Shift, Information ...",SUPPORT CENTER\n\nIF YOU ARE A CURRENT ADVENTI...,"['troubleshooting', 'ticketing system', 'appli..."
223,INFORMATION-TECHNOLOGY,Information Technology Specialist,COMPANY DESCRIPTION\n ENSPYRE MANAGEMENT SERVI...,"['network administration', 'troubleshooting', ..."
224,INFORMATION-TECHNOLOGY,Information Technology Support Technician,THEIR IS A PHYSICAL ASPECT TO THIS JOB THAT TH...,"['technical support', 'hardware installation',..."

In [49]:
print(jobs["job_skill_set"].iloc[0])

['employee relations', 'talent acquisition', 'performance management', 'compensation and benefits', 'employment laws and regulations', 'analytical skills', 'employee benefits administration', 'HR policies and procedures', 'recruitment strategies', 'FMLA', 'ADA', 'communication', 'interpersonal skills', 'collaboration', 'influence', 'change management', 'professional development', 'payroll processing', 'job design', 'salary administration', 'human capital management system', 'HR audits and assessments', 'FLSA', 'ERISA', 'EEOC guidelines', 'confidentiality', 'intellectual curiosity']

In [50]:
jobs["job_skill_set"] = jobs["job_skill_set"].apply(ast.literal_eval)

# **Modelling**

# **Import Model**

In [51]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.12.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.20.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [52]:
from sentence_transformers import SentenceTransformer, util
import torch

In [53]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-MiniLM-L3-v2")

Loading weights:   0%|          | 0/55 [00:00<?, ?it/s]

# **Encoding**

In [54]:
job_embeddings = model.encode(
    jobs["job_description"].tolist(),
    convert_to_tensor=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/37 [00:00<?, ?it/s]

In [55]:
cv_text = "I am a Python Developer with experience in Machine Learning."

cv_embedding = model.encode(
    cv_text,
    convert_to_tensor=True
)

In [56]:
similarities = util.cos_sim(cv_embedding, job_embeddings)

In [57]:
from sentence_transformers import util

scores = util.cos_sim(cv_embedding, job_embeddings)

top_results = scores.topk(k=1)

best_index = top_results.indices[0].item()

best_job = jobs.iloc[best_index]

In [58]:
similarity_scores = util.cos_sim(cv_embedding, job_embeddings)

top_results = torch.topk(similarity_scores[0], k=1)

best_index = top_results.indices[0].item()

best_job = jobs.iloc[best_index]

In [59]:
job_skills = [skill.lower() for skill in best_job["job_skill_set"]]

print(job_skills)

['it fundamentals', 'programming logic', 'networking concepts', 'computer hardware functions', 'comptia a+ certification', 'communication', 'teamwork', 'adaptability', 'conflict resolution', 'mentoring', 'organizational skills', 'engagement', 'professional development', 'student support', 'windows command prompt', 'linux command line', 'powershell', 'audio-visual equipment operation', 'learning management systems (lms)', 'curriculum development', 'mcsa: windows server 2016', 'comptia security+ certification', 'lpic-2 linux professional institute certification', 'diversity awareness']

In [60]:
cv_skills="python,sql"
matched = list(set(cv_skills) & set(job_skills))
missing = list(set(job_skills) - set(cv_skills))

print("Matched Skills:", matched)
print("Missing Skills:", missing)

Matched Skills: []
Missing Skills: ['professional development', 'audio-visual equipment operation', 'curriculum development', 'communication', 'mentoring', 'it fundamentals', 'comptia security+ certification', 'lpic-2 linux professional institute certification', 'windows command prompt', 'student support', 'conflict resolution', 'programming logic', 'linux command line', 'comptia a+ certification', 'computer hardware functions', 'adaptability', 'diversity awareness', 'mcsa: windows server 2016', 'organizational skills', 'learning management systems (lms)', 'networking concepts', 'powershell', 'teamwork', 'engagement']

In [61]:
skills_score = (len(matched) / len(job_skills)) * 100

print(f"Skills Match Score: {skills_score:.2f}%")

Skills Match Score: 0.00%

In [62]:
recommendation_dict = {
    "etl": "Learn ETL tools like SSIS, Apache Airflow, or Talend.",
    "cloud technologies": "Gain hands-on experience with AWS, Azure, or Google Cloud.",
    "data warehousing": "Study data warehouse concepts and practice with Snowflake or BigQuery.",
    "data security": "Learn database security, encryption, and access control.",
    "docker": "Learn Docker basics and containerize one of your projects.",
    "git": "Use Git and GitHub in your projects to demonstrate version control skills."
}

In [63]:
for skill in missing:
    if skill in recommendation_dict:
        print("•", recommendation_dict[skill])
    else:
        print(f"• Consider improving your {skill} skill.")

• Consider improving your professional development skill.
• Consider improving your audio-visual equipment operation skill.
• Consider improving your curriculum development skill.
• Consider improving your communication skill.
• Consider improving your mentoring skill.
• Consider improving your it fundamentals skill.
• Consider improving your comptia security+ certification skill.
• Consider improving your lpic-2 linux professional institute certification skill.
• Consider improving your windows command prompt skill.
• Consider improving your student support skill.
• Consider improving your conflict resolution skill.
• Consider improving your programming logic skill.
• Consider improving your linux command line skill.
• Consider improving your comptia a+ certification skill.
• Consider improving your computer hardware functions skill.
• Consider improving your adaptability skill.
• Consider improving your diversity awareness skill.
• Consider improving your mcsa: windows server 2016 skill.
• Consider improving your organizational skills skill.
• Consider improving your learning management systems (lms) skill.
• Consider improving your networking concepts skill.
• Consider improving your powershell skill.
• Consider improving your teamwork skill.
• Consider improving your engagement skill.

# **deployment**

In [64]:
!pip install -q streamlit pyngrok sentence-transformers pdfplumber

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 18.2 MB/s eta 0:00:00

In [65]:
%%writefile app.py

import streamlit as st
import pdfplumber
import pandas as pd
import ast

from sentence_transformers import SentenceTransformer, util

# -----------------------------
# Page Config
# -----------------------------

st.set_page_config(
    page_title="AI Resume Matcher",
    page_icon="💼",
    layout="wide"
)

# -----------------------------
# Custom CSS
# -----------------------------

st.markdown("""
<style>

.main{
    background-color:#F5F7FB;
}

.big-title{
    font-size:42px;
    font-weight:bold;
    color:#2E3A59;
    text-align:center;
}

.subtitle{
    text-align:center;
    color:gray;
    font-size:18px;
}

.result{
    background:#ffffff;
    padding:20px;
    border-radius:15px;
    box-shadow:0px 3px 12px rgba(0,0,0,0.1);
}

</style>
""",unsafe_allow_html=True)

st.markdown("<p class='big-title'>💼 AI Resume Matcher</p>",unsafe_allow_html=True)

st.markdown(
"<p class='subtitle'>Upload your CV and discover the most suitable job.</p>",
unsafe_allow_html=True
)

# -----------------------------
# Load Model
# -----------------------------

@st.cache_resource
def load_model():
    return SentenceTransformer("all-MiniLM-L6-v2")

model = load_model()

# -----------------------------
# Load Dataset
# -----------------------------

@st.cache_data
def load_jobs():

    jobs = pd.read_csv("all_job_post.csv")

    jobs = jobs[['category',
                 'job_title',
                 'job_description',
                 'job_skill_set']]

    jobs.dropna(inplace=True)

    jobs.drop_duplicates(inplace=True)

    jobs["job_skill_set"] = jobs["job_skill_set"].apply(ast.literal_eval)

    return jobs

jobs = load_jobs()

# -----------------------------
# Upload CV
# -----------------------------

uploaded_file = st.file_uploader(
    "📄 Upload Your CV",
    type="pdf"
)

# -----------------------------
# Read PDF
# -----------------------------

def read_pdf(pdf):

    text=""

    with pdfplumber.open(pdf) as pdf_file:

        for page in pdf_file.pages:

            if page.extract_text():

                text += page.extract_text()

    return text

# -----------------------------
# Prediction
# -----------------------------

if uploaded_file:

    cv_text = read_pdf(uploaded_file)

    with st.spinner("Analyzing Resume..."):

        cv_embedding = model.encode(cv_text,
                                    convert_to_tensor=True)

        job_embeddings = model.encode(
            jobs["job_description"].tolist(),
            convert_to_tensor=True
        )

        similarities = util.cos_sim(
            cv_embedding,
            job_embeddings
        )[0]

        best_index = similarities.argmax().item()

        best_job = jobs.iloc[best_index]

        score = similarities[best_index].item()*100

    st.success("Analysis Finished ✅")

    st.markdown("---")

    col1,col2=st.columns(2)

    with col1:

        st.metric(
            " Match Score",
            f"{score:.2f}%"
        )

    with col2:

        st.metric(
            "💼 Best Job",
            best_job["job_title"]
        )

    st.markdown("---")

    st.subheader("📋 Job Description")

    st.write(best_job["job_description"])

    st.markdown("---")

    job_skills = [
        s.lower()
        for s in best_job["job_skill_set"]
    ]

    cv_lower = cv_text.lower()

    matched=[]

    missing=[]

    for skill in job_skills:

        if skill in cv_lower:

            matched.append(skill)

        else:

            missing.append(skill)

    skills_score=(len(matched)/len(job_skills))*100

    st.progress(skills_score/100)

    st.write(
        f"### Skills Match : {skills_score:.2f}%"
    )

    c1,c2=st.columns(2)

    with c1:

        st.success("✅ Matched Skills")

        st.write(matched)

    with c2:

        st.error("❌ Missing Skills")

        st.write(missing)

Writing app.py

In [66]:
from pyngrok import ngrok

ngrok.set_auth_token("")

In [67]:
!pkill streamlit

In [68]:
!nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &

nohup: appending output to 'nohup.out'

In [69]:
from pyngrok import ngrok

ngrok.kill()

In [70]:
public_url = ngrok.connect(8501)

print(public_url)

ERROR:pyngrok.process.ngrok:t=2026-07-16T14:40:02+0000 lvl=eror msg="failed to reconnect session" obj=tunnels.session err="authentication failed: This ngrok session is not authenticated. ngrok requires an account and a valid credential to start a session.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nGet your credential: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"
ERROR:pyngrok.process.ngrok:t=2026-07-16T14:40:02+0000 lvl=eror msg="session closing" obj=tunnels.session err="authentication failed: This ngrok session is not authenticated. ngrok requires an account and a valid credential to start a session.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nGet your credential: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"
ERROR:pyngrok.process.ngrok:t=2026-07-16T14:40:02+0000 lvl=eror msg="terminating with error" obj=app err="authentication failed: This ngrok session is not authenticated. ngrok requires an account and a valid credential to start a session.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nGet your credential: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"
CRITICAL:pyngrok.process.ngrok:t=2026-07-16T14:40:02+0000 lvl=crit msg="command failed" err="authentication failed: This ngrok session is not authenticated. ngrok requires an account and a valid credential to start a session.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nGet your credential: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"

PyngrokNgrokError: The ngrok process errored on start: authentication failed: This ngrok session is not authenticated. ngrok requires an account and a valid credential to start a session.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nGet your credential: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n.